version: '3.8'

services:
  # PostgreSQL 데이터베이스
  postgres:
    image: postgres:15
    container_name: cleanbox_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - cleanbox_network

  # Ollama AI 서비스
  ollama:
    image: ollama/ollama:latest
    container_name: cleanbox_ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - cleanbox_network
    command: >
      sh -c "
        ollama serve &
        sleep 10 &&
        ollama pull llama2 &&
        wait
      "

  # CleanBox 웹 애플리케이션
  cleanbox:
    build: .
    container_name: cleanbox_app
    environment:
      - FLASK_APP=${FLASK_APP}
      - FLASK_ENV=${FLASK_ENV}
      - FLASK_PORT=${FLASK_PORT}
      - CLEANBOX_USE_OLLAMA=${CLEANBOX_USE_OLLAMA}
      - OLLAMA_URL=${OLLAMA_URL}
      - OLLAMA_MODEL=${OLLAMA_MODEL}
      - CLEANBOX_DATABASE_URI=${CLEANBOX_DATABASE_URI}
      - CLEANBOX_SECRET_KEY=${CLEANBOX_SECRET_KEY}
      - CLEANBOX_ENCRYPTION_KEY=${CLEANBOX_ENCRYPTION_KEY}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_REDIRECT_URI=${GOOGLE_REDIRECT_URI}
      - OAUTHLIB_INSECURE_TRANSPORT=${OAUTHLIB_INSECURE_TRANSPORT}
    ports:
      - "5001:5001"
    depends_on:
      - postgres
      - ollama
    networks:
      - cleanbox_network
    volumes:
      - ./instance:/app/instance
    restart: unless-stopped

volumes:
  postgres_data:
  ollama_data:

networks:
  cleanbox_network:
    driver: bridge 