version: '3.8'

services:
  # 테스트용 PostgreSQL 데이터베이스
  postgres_test:
    image: postgres:15
    container_name: cleanbox_postgres_test
    environment:
      POSTGRES_DB: cleanbox_test
      POSTGRES_USER: cleanbox_user
      POSTGRES_PASSWORD: cleanbox_password
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"  # 테스트용 포트
    networks:
      - cleanbox_test_network

  # 테스트용 Ollama AI 서비스
  ollama_test:
    image: ollama/ollama:latest
    container_name: cleanbox_ollama_test
    ports:
      - "11435:11434"  # 테스트용 포트
    volumes:
      - ollama_test_data:/root/.ollama
    networks:
      - cleanbox_test_network

volumes:
  postgres_test_data:
  ollama_test_data:

networks:
  cleanbox_test_network:
    driver: bridge 